# Generated by Django 2.1.3 on 2018-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_id',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_intro',
            field=models.TextField(max_length=100),
        ),
    ]
