# Generated by Django 2.1.3 on 2018-11-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0002_auto_20181126_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='major_review',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
