# Generated by Django 2.1.3 on 2018-12-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0003_major_review_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='major_intro',
            new_name='major_introduction',
        ),
    ]
