# Generated by Django 2.1.3 on 2018-11-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
