# Generated by Django 2.1.3 on 2018-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181130_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
