# Generated by Django 2.1.3 on 2018-11-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181122_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='high_major',
            field=models.IntegerField(choices=[[1, '인문사회'], [2, '자연과학'], [3, '예체능'], [4, '공학'], [5, '의학']]),
        ),
    ]
