# Generated by Django 2.1.3 on 2018-12-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181203_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='high_major',
            new_name='major',
        ),
    ]
