# Generated by Django 2.1.3 on 2018-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20181203_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
