# Generated by Django 2.1.3 on 2018-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181130_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_major',
            field=models.CharField(choices=[('language', '언어/문학'), ('human', '인문학')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
