# Generated by Django 2.1.3 on 2018-11-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0002_university_major_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_review',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university_review',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_infor.University_major_data'),
        ),
    ]
