# Generated by Django 2.1.3 on 2018-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0003_auto_20181126_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_major_data',
            name='university',
        ),
        migrations.RemoveField(
            model_name='university_review',
            name='content',
        ),
        migrations.AddField(
            model_name='university_review',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university_review',
            name='major',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='University_major_data',
        ),
    ]
