# Generated by Django 2.1.3 on 2018-12-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0003_auto_20181203_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_major_data',
            name='university',
        ),
        migrations.RemoveField(
            model_name='university_review',
            name='major',
        ),
        migrations.DeleteModel(
            name='University_major_data',
        ),
    ]
