# Generated by Django 2.1.3 on 2018-11-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0004_auto_20181127_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='University_major_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.TextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_infor.University')),
            ],
        ),
        migrations.AddField(
            model_name='university_review',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university_review',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_infor.University_major_data'),
        ),
    ]
