# Generated by Django 2.1.3 on 2018-12-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_infor', '0007_auto_20181203_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_review',
            name='major',
            field=models.CharField(choices=[('language', '언어/문학'), ('인문학', '인문학'), ('경영/경제', '경영/경제'), ('l', '법학'), ('sc', '사회과학'), ('e', '교육'), ('aa', '농림/수산'), ('clse', '화학/생명/과학/환경'), ('domestic', '생활과학'), ('math', '수학/물리/천문/지구'), ('nursing', '간호'), ('sanitation', '보건'), ('weed', '약학'), ('medical', '의료예과'), ('educa', '교육'), ('elatric', '전기/전자/컴퓨터'), ('construction', '건설'), ('industial', '산업/안전'), ('ingredient', '재료'), ('mechanic', '기계'), ('chemical_eng', '화공/고분자/에너지'), ('eng_edu', '공학교육'), ('dacne', '무용/체육'), ('acting', '연극/영화'), ('application_art', '응용예술'), ('art', '미술'), ('music', '음악'), ('medical', '의료')], max_length=20),
        ),
    ]
